config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'articles#index'
  resources :articles do
    resources :procedures
    resources :comments
    resources :favorites, only: [:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get :search
      post :confirm
    end
    member do
      get :task
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: %i[index create destroy]

  def index
    @favorites = current_user.favorites
  end

  def create
    @article = Article.find(params[:article_id])
    Favorite.create(user_id: current_user.id, article_id: params[:article_id])
  end

  def destroy
    @article = Article.find(params[:article_id])
    Favorite.find_by(user_id: current_user.id, article_id: params[:article_id]).destroy
  end
end

app/views/favorites/_favorite.html.erb
<% if !user_signed_in? %>
  <%= article.favorites.length %>
<% elsif current_user.favorited_by?(article.id) %>
  <%= link_to article_favorite_path(article, article.favorites),class: "favorite-link", method: :delete, remote: true do %>
    <i class="fa-solid fa-star"></i>
  <% end %>
  <%= article.favorites.length %>
<% else %>
  <%= link_to article_favorites_path(article),class: "favorite-link", method: :post, remote: true do %>
    <i class="fa-regular fa-star"></i>
  <% end %>
  <%= article.favorites.length %>
<% end %>

app/views/favorites/_form.html.erb
<div id = "favorite_<%= @article.id %>">
<% unless @article.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入り', favorites_path(article_id: @article.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
</div>

app/views/favorites/create.js.erb
$('#favorite_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { article: @article }) %>");

app/views/favorites/destroy.js.erb
$('#favorite_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { article: @article }) %>");

app/views/favorites/index.html.erb
<header>
  <div class="jumbotron text-center hero " style="background:url(<%= asset_path 'file6.jpg' %>); background-size:cover; background-position:center bottom;">
    <div class="container">
      <h2 class="favorites mb-3">お気に入りの記事をストックしてみよう</h2>
      <h4 class="favorites mt-5">↓ お気に入り一覧はこちら ↓</h4>
    </div>
  </div>
</header>

<div class="container", style="margin-bottom: 300px;">
  <div class="row col-md-12 justify-content-center">
    <table>
      <thead>
        <tr>
          <th>サムネイル</th>
          <th>タイトル</th>
          <th>ユーザー</th>
        </tr>
      </thead>

      <tbody>
        <div class="card mb-4 text-center" >
          <div class="row no-gutters">
            <div class="col-md-3">
              <% @favorites.each do |favorite| %>
                <tr>
                  <td class="favorites">
                  <% if favorite.article.image? %>
                    <%= link_to (image_tag favorite.article.image.url, size: '100x100'), favorite.article %>
                  <% else %>
                    <%= link_to (image_tag 'no_image.png', size: '100x100'), favorite.article %>
                  <% end %>
                  <td><%= favorite.article.title %></td>
                  <td><%= link_to favorite.article.user.name, user_path(favorite.user),class: "link-to mx-4" %></td>
                  <td>投稿日:<%= favorite.article.created_at.strftime("%Y/%m/%d") %></td>
                </tr>
              <% end %>
            </div>
          </div>
        </div>
      </tbody>
    </table>
  </div>
</div>