config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'articles#index'
  resources :articles do
    resources :procedures
    resources :comments
    resources :favorites, only: [:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get :search
      post :confirm
    end
    member do
      get :task
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :procedures, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories, source: :category
  
  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :procedures, allow_destroy: true, reject_if: :all_blank

  enum status: { public: 0, draft: 1, private: 2 }, _prefix: true
  validates_associated :procedures

  ransacker :likes_count do
    query = '(SELECT COUNT(likes.article_id) FROM likes where likes.article_id = articles.id GROUP BY likes.article_id)'
    Arel.sql(query)
  end

  validates :title, presence: true, length: { maximum: 255 }
  validates :status, presence: true
  validates :procedures, associated: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show task edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  def index
    if params[:q].present?
      @articles = Article.all.page(params[:page])
      @article_search = @articles.ransack(params[:q])
      @articles = @article_search.result(distinct: true).order(updated_at: "DESC").page(params[:page])
    else
      params[:q] = { sorts: 'updated_at DESC' }
      @articles = Article.all.page(params[:page])
      @article_search = @articles.ransack(params[:q])
      @articles = @article_search.result(distinct: true).order(updated_at: "DESC").page(params[:page])
    end
    @count = @articles.where(status:'public').total_count
  end

  def show
    @articles = Article.all
    @procedures = @article.procedures
    @comments = @article.comments
    @comment = @article.comments.build
    @favorite = current_user.favorites.find_by(article_id: @article.id) if  user_signed_in?
    if @article.status_private? && @article.user != current_user
      redirect_to articles_path, notice: 'このページは非公開のためアクセスできません'
    end
  end

  def task
    @articles = Article.all
    @procedures = @article.procedures
    @comments = @article.comments
    @comment = @article.comments.build
    @favorite = current_user.favorites.find_by(article_id: @article.id) if  user_signed_in?
    if @article.status_private? && @article.user != current_user
      redirect_to articles_path, notice: 'このページは非公開のためアクセスできません'
    end
  end

  def new
    @article = Article.new
    @procedure = @article.procedures.build
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.build(article_params)
    if params[:back]
      render :new
    else
      if @article.save
        redirect_to article_path(@article), notice: "作成しました"
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    if @article.update(article_params)
      redirect_to article_url(@article), notice: "投稿した記事を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: "投稿した記事を削除しました"
  end

  def confirm
    @article = current_user.articles.build(article_params)
    if params[:back]
      render :new if @article.invalid?
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :image, :image_cache, :status, :deadline, :date, :user_id, { category_ids: [] }, procedures_attributes: [:image, :image_cache, :content, :article_id, :user_id, :_destroy, :id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_articles_path
    elsif action_name == 'edit'
      article_path
    end
  end
end

app/views/articles/_form.html.erb
<div class="container mt-5 mb-5">
  <div class="row col-md-8 mx-auto">
    <%= form_with(model: @article, local: true ,url: choose_new_or_edit ) do |form| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "件のエラー") %> により投稿ができませんでした！</h2>

          <ul>
            <% article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field mb-4">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: 'タイトルを入力'%>
      </div>

      <div class="field mb-5">
        <%= form.label :image %>
        <%= image_tag(article.image.url) if article.image && article.image.url %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
      </div>

      <div class="field mb-5">
        <h5 class="category mb-4">↓ カテゴリを選択してください ↓</h5>
        <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
          <%= b.label { b.check_box + b.text } %>
        <% end %>
      </div>

      <div class="field mb-2" id="article_status_id">
          <%= form.select :status, Article.statuses.map { |k, v| [t("article.status.#{k}"), k] }, selected: @article.status %>
      </div>
      <p>投稿：投稿をする</p>
      <p>下書き：下書きで保存する</p>
      <p>やること：やることリストとして保存する</p>

      <div class="box-procedure" style="margin-left: 10px;">
        <h4 class="ml-5">[ やること ]を選択した場合に入力</h4>
        <div class="container mt-5">
          <p>※ 作業日には、作業する(した)日を入力してください</p>
          <div class="field mb-4">
            <%= form.label :date %>
            <p class="description m-0"><%= form.date_field :date %> ※ 非公開を選択時のみ選択してください</p>
          </div>

          <p>※ 期限には、作業を終わらせたい日を入力してください</p>

          <div class="field">
            <%= form.label :deadline %>
            <p class="description m-0"><%= form.date_field :deadline %> ※ 非公開を選択時のみ選択してください</p>
          </div>
        </div>
      </div>

      <%= form.hidden_field :user_id, :value => current_user.id%>

      <h3 class="form-title mt-5 mb-3">〜 内容（手順） 〜</h3>
      <p class="description m-0">以下に内容を入力してください</p>
      <p> ※ 以下の『追加ボタン』を押すと入力フォームが追加されます</p>

      <%= form.fields_for :procedures do |f| %>
        <div class="field">
          <%= f.label :'画像' %>
          <%= f.file_field :image %>
          <%= f.hidden_field :image_cache %>
        </div>

        <div class="field">
          <%= f.label :'内容' %>
          <%= f.text_area :content, placeholder: 'ここに入力してください。必要に応じて入力フォームを追加してください' %>
        </div>
      <% end %>

      <div class="add-botton-box my-4">
        <%= link_to_add_association "〜 追加ボタン 〜", form, :procedures,
        class: 'add_fields' 'btn btn-info',
        id: 'add-btn',
        data: {
          association_insertion_node: '#detail-association-insertion-point',
          association_insertion_method: 'before'
          }
        %>
      </div>

      <div id="detail-association-insertion-point"></div>

      <div class="actions">
        <%= form.submit class: 'btn btn-primary', style:" margin-bottom: 200px;" %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_procedure_fields.html.erb
<div class="nested-fields">
    <div class="field">
      <%= f.label :'画像' %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>

      <div class="field">
      <%= f.label :'内容' %>
      <%= f.text_area :content, placeholder: 'ここに入力してください' %>
    </div>

  <%= link_to_remove_association "削除", f %>
</div>

app/views/articles/confirm.html.erb
<div class="container mt-5">
  <div class="row col-md-8 mx-auto">
    <h3>以下の内容で、投稿します</h3>
    <% if @article.status == 'private' %>
      <h5 class="title mt-5">~ この記事は非公開です ~</h5>
    <% end %>
  </div>
</div>

<div class="container mb-5">
  <div class="row col-md-8 mx-auto">
    <%= form_with(model: @article, url: articles_path, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :image %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :category %>
      <%= form.hidden_field :status %>
      <%= form.hidden_field :date %>
      <%= form.hidden_field :deadline %>

      <h4 class="mt-5">タイトル:<%= @article.title %></h4>

      <p class="mt-3">サムネイル</p>
      <% if @article.image? %>
        <%= image_tag @article.image.url, class: "confirm_article_image" %>
      <% else %>
        <%= image_tag 'no_image.png', size: '200x150', class: "confirm_article_image" %>
      <% end %>

      <h4 class="mt-5 mb-3">選択したカテゴリ</h4>
          <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
            <%= b.label { b.check_box + b.text } %>
        <% end %>

          <h4 class= "mt-5">入力した内容</h4>
      <div class="container col-md-9 mx-auto text-center bg-light">
        <div class="row">
          <% n = 0 %>
          <%= form.fields_for :procedures do |procedure| %>
            <div class="col-md-3 mx-auto">
            <%= procedure.hidden_field :image %>
            <%= procedure.hidden_field :image_cache %>
            <%= procedure.hidden_field :content %>

              <% if procedure.object.image? %>
              <h4> 手順<%= n += 1 %> </h4>
                <%= image_tag procedure.object.image.url, class: "procedure_image" %>
              <% else %>
                <%= image_tag 'no_image.png', size: '300x200', class: 'procedure_image' %>
              <% end %>
              <h4><%= procedure.object.content %></h4>
            </div>
          <% end %>
        </div>
      </div>

          <% if @article.date? %>
          <p>作業日:<%= @article.date.strftime("%Y/%m/%d") %></p>
          <% end %>

          <% if @article.deadline? %>
          <p>期限:<%= @article.deadline.strftime("%Y/%m/%d") %></p>
          <% end %>

      <%= form.submit  "登録する", class: 'btn btn-primary', style: " margin-bottom: 200px;" %>

      <%= form.submit "戻る", name: 'back', class: 'btn btn-info', style:" margin-bottom: 200px;" %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="mt-5">編集</h1>
    <%= link_to '詳細画面へ戻る', @article, class: "btn btn-success mt-5 mb-5 ml-5" %>
  </div>
</div>

<div class="container">
  <div class="row mb-5">
    <%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/index.html.erb
<tbody>
  <div class="container-fluid col-md-10">
    <div class="row">
      <div class="col-md-3">
        <h3>検索</h3>
        <%= search_form_for @article_search  do |f| %>
          <%= f.search_field :title_cont, placeholder: 'タイトル検索' %>
          <%= f.submit '検索' %><br>
          <%= f.collection_check_boxes :categories_id_in, Category.all, :id ,:name %>
          <%= f.select( :sorts, { '並び替え': '並び替え', '古い順': 'updated_at asc', '新しい順': 'updated_at desc' } , { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()'} ) %>
        <% end %>

        <br><hr>
        <thead>
          <% if @article_search.present? %>
            <p>表示件数：<%= @count %>件</p>
          <% end %>
          <div class="simple-calendar mt-5">
            <%= month_calendar(attribute: :deadline, events: @articles) do |date, articles| %>
              <%= date.day %>
              <% articles.each do |article| %>
                <div>
                  <% if articles == current_user.articles.find_by(status: 'private') %>
                    <%= link_to article.title, task_article_path(article) %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </thead>
      </div>

      <div class="col-md-9">
        <div class="card-deck">
          <% @articles.each do |article| %>
            <% if article.status == "public" %>
              <div class="col-md-3 my-2">
                <div class="card text-center h-100">
                  <% if article.image? %>
                    <%= link_to (image_tag article.image.url ,size: '230x200', class: 'img_wrap mx-auto d-block'), article %>
                  <% else %>
                    <%= link_to (image_tag 'no_image.png', size: '230x200', class: 'img_wrap mx-auto d-block'), article %>
                  <% end %>
                  <p><%= article.title %></p>
                  <p>
                  <% article.categories.each do |category| %>
                    <%= category.name %>
                  <% end %>
                  </p>
                  <p><%= link_to article.user.name, user_path(article.user), class: "link-to" %></p>
                  <p>更新日時:<%= article.updated_at.strftime("%Y/%m/%d") %><i class="fa fa-heart unlike-btn ml-4"></i><%= article.liked_users.count %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</tbody>
<div class="container">
  <div class="row col-md-10 justify-content-center mt-5">
    <div class='p-top__paginate' style="margin-bottom: 300px;"><%= paginate @articles %></div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container mt-5">
  <div class="row">
    <h1>入力画面</h1>
    <h4 class="new my-5"></h4>
  </div>
</div>

<div class="container">
  <div class="row">
    <%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container mb-5">
  <div class="row">
    <% if @article.status == 'private' %>
      <h3 class="title mt-5">この記事は非公開です</h3>
    <% end %>
  </div>
  <% if @article.status == 'private' %>
    <h4>~目標の期日までに終わらせましょう~</h4>
  <% end %>
</div>

<div class="container mb-5">
  <div class="row">
    <h3 class="title">記事の詳細ページ</h3>
  </div>
</div>

<div class="container">
  <h3 class="title mb-4">タイトル：<%= @article.title %></h3>
  <div class="row">
    <div class="col-md-4 mx-auto">
    <% if @article.image? %>
      <%= image_tag @article.image.url, class: "article_image" %>
    <% else %>
      <%= image_tag 'no_image.png', class: "article_image" %>
    <% end %>
    </div>

    <div class=" col-md-8 mx-auto">
      <h4 class="mr-3">カテゴリ:</h4>
      <% @article.categories.each do |category| %>
        <h4 class="mr-3">□<%= category.name %></h4>
      <% end %>
    </div>
  </div><hr>
</div>

<div class="container col-md-9 mx-auto text-center bg-light">
  <div class="row">
      <% @procedures.each.with_index(1) do |procedure, index|%>
          <div class="col-md-3 mx-auto">
        <h4>No.<%= "#{index}" %></h4>
        <p>
          <% if procedure.image? %>
            <%= image_tag procedure.image.url, class: "procedure_image", size: '200x200' %>
          <% else %>
            <%= image_tag 'no_image.png', size: '200x200', class: 'procedure_image' %>
          <% end %>
        </p>
        <p>
          <h5 class="m-auto"><%=safe_join(procedure.content.split("\n"),tag(:br))%></h5>
        </p>
    </div>
      <% end %>
  </div>
</div>

<div class="container mt-5">
  <div class="row col-md-8 mx-auto">
    <% if @article.status == 'private' %>
    <p>
      <h5>作業日:</h5>
      <h6 class="mt-1 mr-3"><%= @article.date.strftime("%Y/%m/%d") %></h4>
    </p>

    <p>
      <h5>期限:</h5>
      <h6 class="mt-1"><%= @article.deadline.strftime("%Y/%m/%d") %></h6>
    </p>
    <% end %>

<div class="container mt-5">
  <div class="row col-md-10 mx-auto">
    <% if user_signed_in? %>
      <div id = "favorite_<%= @article.id %>" class="mr-3">
        <%= render partial: 'favorites/favorite', locals: { article: @article } %>
      </div>

      <div id = "like_<%= @article.id %>" class="mr-3">
        <%= render partial: "likes/like", locals: { article: @article } %>
      </div>

      <p class="mr-3">投稿者:<%= link_to @article.user.name, user_path(@article.user) %></p>

    <% if user_signed_in? && @article.user == current_user %>
      <a class= "mr-2" ><%= link_to '編集', edit_article_path(@article), class: "btn btn-success"%></a>
      <a class= "mr-3" ><%= link_to '削除', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></a>
    <% end %>

      <% unless @article.user_id == current_user.id %>
        <%= render 'users/follow_form', user: @article.user %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container mt-5" style=" margin-bottom: 200px;">
  <div class="row col-md-8 mx-auto">
    <p>コメント一覧</p>

    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, article: @article } %>
    </div>

    <%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>
  </div>
</div>

app/views/articles/task.html.erb
<div class="container mb-5">
  <div class="row">
    <h3 class="title mt-5 mx-auto">タスク管理用ページです</h3>
  </div>
</div>

<div class="container-fluid col-md-10">
  <div class="row">
    <div class="col-ml-md-2 mx-auto">
      <div class="simple-calendar mt-5">
        <%= month_calendar(attribute: :deadline, events: @articles) do |date, articles| %>
          <%= date.day %>
          <% articles.each do |article| %>
            <div>
              <%= link_to article.title, task_article_path(article) %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 mx-auto">
      <div class="container">
        <h3 class="title mb-4">タイトル：<%= @article.title %></h3>
        <div class="row">
          <div class="col-md-4 mx-auto">
            <% if @article.image? %>
              <%= image_tag @article.image.url, class: "article_image" %>
            <% else %>
              <%= image_tag 'no_image.png', class: "article_image" %>
            <% end %>
          </div>

          <div class=" col-md-8 mx-auto">
            <h4 class="mr-3">カテゴリ:</h4>
            <% @article.categories.each do |category| %>
              <h4 class="mr-3">□<%= category.name %></h4>
            <% end %>
          </div>
        </div><hr>
      </div>

      <div class="container col-md-9 mx-auto text-center bg-light">
        <div class="row">
            <% @procedures.each.with_index(1) do |procedure, index|%>
              <div class="col-md-3 mx-auto">
              <h4>No.<%= "#{index}" %></h4>
              <p>
                <% if procedure.image? %>
                  <%= image_tag procedure.image.url, class: "procedure_image", size: '200x200' %>
                <% else %>
                  <%= image_tag 'no_image.png', size: '200x200', class: 'procedure_image' %>
                <% end %>
              </p>
              <p>
                <h5 class="m-auto"><%=safe_join(procedure.content.split("\n"),tag(:br))%></h5>
              </p>
              </div>
            <% end %>
        </div>
      </div>

      <div class="container mt-5">
        <div class="row col-md-10 mx-auto">
          <% if @article.status == 'private' %>
            <p>
              <h5>作業日:</h5>
              <h6 class="mt-1 mr-3"><%= @article.date.strftime("%Y/%m/%d") %></h4>
            </p>

            <p>
              <h5>期限:</h5>
              <h6 class="mt-1"><%= @article.deadline.strftime("%Y/%m/%d") %></h6>
            </p>
          <% end %>

          <div class="container mt-5">
            <div class="row">
              <% if user_signed_in? %>
                <% if user_signed_in? && @article.user == current_user %>
                  <a class= "mr-2" ><%= link_to '編集', edit_article_path(@article), class: "btn btn-success"%></a>
                  <a class= "mr-3" ><%= link_to '削除', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></a>
                <% end %>
                <% unless @article.user_id == current_user.id %>
                  <%= render 'users/follow_form', user: @article.user %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container mt-5" style=" margin-bottom: 200px;">
  <div class="row col-md-8 mx-auto">
    <p>コメント一覧</p>

    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, article: @article } %>
    </div>

    <%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>
  </div>
</div>