config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'articles#index'
  resources :articles do
    resources :procedures
    resources :comments
    resources :favorites, only: [:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get :search
      post :confirm
    end
    member do
      get :task
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_articles, through: :likes, source: :article
  has_many :favorites, dependent: :destroy
  has_many :favorited_articles, through: :favorites, source: :article
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :image, ImageUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'ゲストユーザー'
    end
  end

  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = '管理者ゲストユーザー'
      user.admin = true
    end
  end

  def liked_by?(article_id)
    likes.where(article_id: article_id).exists?
  end

  def favorited_by?(article_id)
    favorites.where(article_id: article_id).exists?
  end

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]
  before_action :ensure_admin_user, only: %i[update destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザーの内容を更新しました"
    else
      flash.now[:danger] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  def ensure_admin_user
    if resource.email == 'admin_guest@example.com'
      redirect_to root_path, alert: '管理者ゲストユーザーの更新・削除はできません。'
    end
  end


  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private
def user_params
  params.require(:user).permit(:name, :email, :profile, :image, :image_cache)
end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def new_admin_guest
    user = User.admin_guest
    sign_in user
    redirect_to root_path, notice: '管理者ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ followings followers ]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザーの内容を更新しました"
    else
      flash.now[:danger] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  def followings
    @users = @user.following
  end

  def followers
    @users = @user.followers
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :profile, :image, :image_cache)
  end

end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id))  do |form| %>
      <%= form.hidden_field :followed_id %>
      <%= form.submit "フォロー", class: "btn btn-info" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |form| %>
      <%= form.submit "フォロー中", class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="jumbotron text-center hero " style="background:url(<%= asset_path 'file6.jpg' %>); background-size:cover; background-position:center bottom;">
  <div class="container">
    <h2 class="followers mb-3">共有仲間を増やしていこう！</h2>
    <p class="followers">↓ フォロー 一覧はこちら ↓</p>
    <%= link_to "フォロー", followings_user_path(@user), class: "btn btn-primary" %>
  </div>
</div>

<div class="container">
  <div class="row col-md-12 justify-content-center">
    <h3 class="text-center">フォロワー一覧</h3>
  </div>
</div>

<div class="container">
  <div class="row col-md-12 justify-content-center">
    <p><%= @user.followers.count %>フォロー</p>
  </div>
</div>

<div class="container", style="margin-bottom: 300px;">
  <div class="row col-md-12 justify-content-center">
    <table>
      <tbody>
        <div class=" mb-4 text-center" >
          <div class="row no-gutters">
            <div class="col-md-3">
              <% @users.each do |user| %>
                <tr>
                  <td><%= link_to user.name, user, class: "link-to mr-3" %></td>
                  <td><%= render 'follow_form', user: user %></td>
                </tr>
              <% end %>
            </div>
          </div>
        </div>
      </tbody>
    </table>
  </div>
</div>

app/views/users/followings.html.erb
<header>
  <div class="jumbotron text-center hero " style="background:url(<%= asset_path 'file6.jpg' %>); background-size:cover; background-position:center bottom;">
    <div class="container">
      <h2 class="followings mb-3">共有仲間を増やしていこう！</h2>
      <p class="followings">↓ フォロワー 一覧はこちら ↓</p>
      <%= link_to "フォロワー", followers_user_path(@user), class: "btn btn-primary" %>
    </div>
  </div>
</header>

<div class="container">
  <div class="row col-md-12 justify-content-center">
    <h3>フォロー一覧</h3>
  </div>
</div>

<div class="container">
  <div class="row col-md-12 justify-content-center">
    <p><%= @user.following.count %>フォロー</p><br>
  </div>
</div>

<div class="container", style="margin-bottom: 300px;">
  <div class="row col-md-12 justify-content-center">
    <table>
      <tbody>
        <div class=" mb-4 text-center" >
          <div class="row no-gutters">
            <div class="col-md-3">
              <% @users.each do |user| %>
                <tr>
                  <td><%= link_to user.name, user, class: "link-to" %></td>
                  <td><%= render 'follow_form', user: user %></td>
                </tr>
              <% end %>
            </div>
          </div>
        </div>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid col-md-10">
  <div class="row">
    <div class="col-ml-md-2 mx-auto">
      <div class="simple-calendar" style="margin-top: 100px;">
        <% if @user == current_user %>
          <%= month_calendar(attribute: :deadline, events: @user.articles) do |date, articles| %>
            <%= date.day %>
            <% articles.each do |article| %>
              <div>
                <%= link_to article.title, task_article_path(article) %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 mx-auto">
      <div class="container mt-5">
        <div class="row m-auto">
          <% if user_signed_in? && @user == current_user %>
            <h1>マイページ</h1>
          <% else %>
            <h1 class="mr-4"><%= @user.name %>さんのページ</h1>
            <%= render 'follow_form', user: @user %>
          <% end %>
        </div>
      </div>

      <div class="container my-5">
        <div class="row">
          <% if user_signed_in? && @user == current_user %>
            <a class= "mr-3"><%= link_to "プロフィール編集", edit_user_registration_path(current_user), class: "btn btn-success" %></a>
            <a class= "mr-3"><%= link_to "フォロー", followings_user_path(@user), class: "btn btn-primary" %></a>
            <a class= "mr-3"><%= link_to "フォロワー", followers_user_path(@user), class: "btn btn-primary" %></a>
            <a class= "mr-3"><%= link_to "お気に入り", article_favorites_path(@user), class: "btn btn-warning" %></a>
          <% end %>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <% if @user.image? %>
              <%= image_tag @user.image.url, class: 'profile_image',size: '200x200' %>
            <% else %>
              <%= image_tag 'icon.jpeg', class: 'profile_image', size: '200x200' %>
            <% end %>
            <h5>プロフィール画像</h5>
          </div>
          <div class="col-md-6 m-auto">
            <h5>ユーザー名: <%= @user.name %></h5><br>
            <h5>プロフィール</h5>
            <% if @user.profile? %>
              <h5 class="w-break"><%=safe_join(@user.profile.split("\n"),tag(:br))%></h5>
            <% end %>
          </div>
        </div>
      </div>

      <h4 class="profile text-center">↓ <%= @user.name %>さんの投稿 ↓</h4>
      <div class="container mb-4">
        <% @user.articles.each do |article| %>
          <% if article.status == "public" %>
            <div class="card mb-4 text-center" >
              <div class="row no-gutters">
                <div class="col-md-3">
                  <% if article.image? %>
                    <%= link_to (image_tag article.image.url, size: '100x100', class: 'img_wrap m-auto d-block'), article, alt: 'Image' %>
                  <% else %>
                    <%= link_to (image_tag 'no_image.png', size: '100x100', class: 'img_wrap m-auto d-block'), article, alt: 'Image' %>
                  <% end %>
                </div>
                <h3 class=" m-auto"><%= article.title %></h3>
                <p class="m-auto">更新日:<%= article.updated_at.strftime("%Y/%m/%d") %><i class="fa fa-heart unlike-btn ml-4"></i><%= article.liked_users.count %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <% if @user == current_user %>
        <h4 class="profile text-center">↓ <%= @user.name %>さんの下書き ↓</h4>
        <div class="container mb-4">
          <% @user.articles.each do |article| %>
            <% if article.status == "draft" %>
              <div class="card mb-4 text-center" >
                <div class="row no-gutters">
                  <div class="col-md-3">
                    <% if article.image? %>
                      <%= link_to (image_tag article.image.url, size: '100x100', class: 'img_wrap m-auto d-block'), article, alt: 'Image' %>
                    <% else %>
                      <%= link_to (image_tag 'no_image.png', size: '100x100', class: 'img_wrap m-auto d-block'), article, alt: 'Image' %>
                    <% end %>
                  </div>
                  <h3 class=" m-auto"><%= article.title %></h3>
                  <p class="m-auto">更新日:<%= article.updated_at.strftime("%Y/%m/%d") %><i class="fa fa-heart unlike-btn ml-4"></i><%= article.liked_users.count %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>


      <% if @user == current_user %>
        <h4 class="profile text-center">↓ <%= @user.name %>さんのやることリスト ↓</h4>
        <div class="container mb-4">
          <% @user.articles.each do |article| %>
            <% if article.status == "private" %>
              <div class="card mb-4 text-center" >
                <div class="row no-gutters">
                  <div class="col-md-3">
                    <% if article.image? %>
                      <%= link_to (image_tag article.image.url, size: '100x100', class: 'img_wrap m-auto d-block'), task_article_path(article), alt: 'Image' %>
                    <% else %>
                      <%= link_to (image_tag 'no_image.png', size: '100x100', class: 'img_wrap m-auto d-block'), task_article_path(article), alt: 'Image' %>
                    <% end %>
                  </div>
                  <h3 class=" m-auto"><%= article.title %></h3>
                  <p class="m-auto">更新日:<%= article.updated_at.strftime("%Y/%m/%d") %><i class="fa fa-heart unlike-btn ml-4"></i><%= article.liked_users.count %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="push", style=" margin-bottom: 200px;"></div>