config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_guest_sign_in', to: 'users/sessions#new_admin_guest'
  end
  resources :users do
    member do
      get :followings, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root 'articles#index'
  resources :articles do
    resources :procedures
    resources :comments
    resources :favorites, only: [:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get :search
      post :confirm
    end
    member do
      get :task
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WISDOM_app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-light">
      <div class="navbar-brand">
          <%= link_to (image_tag (asset_path'file7.png')), root_path, class: "navbar-brand-item" %>
      </div>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to '管理者画面', rails_admin_path, class: "btn btn-danger"  %>
        <% end %>
        <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-outline-info" %>
        <%= link_to "投稿する", new_article_path, class: "btn btn-outline-info" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
      <% else %>
        <%= link_to "アカウント登録", new_user_registration_path, class: "m-2 btn btn-primary" %>
        <%= link_to "ログイン", new_user_session_path, class: "m-2 btn btn-primary" %>
      <% end %>
    </nav>

    <% if current_page?(root_path) || current_page?(articles_path) %>
      <header>
        <div class="jumbotron text-center hero " style="background:url(<%= asset_path 'file6.jpg' %>); background-size:cover; background-position:center bottom;">
          <div class="container">
            <h4 class="top-jumbotron my-4">
              料理、洗濯、掃除などには手間がかかりますが,少しの工夫で時短や効率化を実現することができます
            </h4>
            <h4 class="top-jumbotron">
              ぜひ、当アプリを利用して家事の時短、効率化に取り組んでみてください
            </h4>
            <% unless user_signed_in? %>
              <div>
                <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path,class: "m-2 btn btn-info", method: :post %>
                <%= link_to '管理者ゲストログイン', users_admin_guest_sign_in_path,class: "m-2 btn btn-info", method: :post %>
              </div>
              <div>
                <%= link_to "アカウント登録", new_user_registration_path, class: "m-2 btn btn-primary" %>
                <%= link_to "ログイン", new_user_session_path, class: "m-2 btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </header>
    <% end %>

  <% if current_page?(new_user_session_path) %>
    <div class="jumbotron text-center hero " style="background:url(<%= asset_path 'file6.jpg' %>); background-size:cover; background-position:center bottom;">
      <div class="container">
        <h2 class="log-in mb-3">ログイン画面</h2>
      </div>
    </div>
  <% end %>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error text-center"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>

      <footer class="footer text-center text-lg-start">
      <div class="text-center pb-3" >
        <p>&copy;2022 Kei Nakamura AllRights Reserved</p>
      </div>
    </footer>
  </body>
</html>